name: job_finder
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  carousel_slider:
  flutter_bloc: 
  google_fonts: 
  font_awesome_flutter: 
  intl_phone_field: 
  image_picker: 
  file_picker: 
  permission_handler: 
  flutter_multi_select_items: 
  dio: 
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  path: ^1.8.3
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  share_plus: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.1



# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icons/
    - assets/images/large_images/
    - assets/files/
    - assets/files/jobs.json

flutter_assets:
  assets_path: assets/images
  output_path: lib/controller/utils
  filename: app_images.dart
  field_prefix:
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
          style: normal
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
